const body =[
  {
    "Name": "3rd age druidic robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 8
  },
  {
    "Name": "3rd age platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-20",
    "ranged": "0",
    "stabdef": "96",
    "slashdef": "108",
    "crushdef": "113",
    "magicdef": "-4",
    "rangedef": "97",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "3rd age range top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "60",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "3rd age robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "24",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "24",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "36",
    "slashdef": "50",
    "crushdef": "61",
    "magicdef": "-3",
    "rangedef": "38",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant platebody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant platebody (h1)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant platebody (h2)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant platebody (h3)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant platebody (h4)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant platebody (h5)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Adamant platebody (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Ahrim's robetop",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "30",
    "ranged": "-10",
    "stabdef": "52",
    "slashdef": "37",
    "crushdef": "63",
    "magicdef": "30",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Ancestral robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "35",
    "ranged": "-8",
    "stabdef": "42",
    "slashdef": "31",
    "crushdef": "51",
    "magicdef": "28",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 2,
    "prayer": 0
  },
  {
    "Name": "Ancient d'hide",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Ancient platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Ancient robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "4",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "4",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Angler top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Ankou top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Antisanta jacket",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Ardougne knight platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "21",
    "slashdef": "20",
    "crushdef": "12",
    "magicdef": "-6",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Armadyl chestplate",
    "stab": -7,
    "slash": -7,
    "crush": -7,
    "magic": "-15",
    "ranged": "33",
    "stabdef": "56",
    "slashdef": "48",
    "crushdef": "61",
    "magicdef": "70",
    "rangedef": "57",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Armadyl d'hide",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Armadyl platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Armadyl robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "4",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "4",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Bandos chestplate",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "-10",
    "stabdef": "98",
    "slashdef": "93",
    "crushdef": "105",
    "magicdef": "-6",
    "rangedef": "133",
    "str": 4,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Bandos d'hide",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Bandos platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Bandos robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "4",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "4",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Banshee top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "22",
    "slashdef": "32",
    "crushdef": "39",
    "magicdef": "-3",
    "rangedef": "24",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black d'hide body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black d'hide body (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black d'hide body (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black desert shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black elegant shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black naval shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black platebody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black platebody (h1)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black platebody (h2)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black platebody (h3)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black platebody (h4)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black platebody (h5)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black platebody (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black robe",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "3",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "3",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black wizard robe (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "3",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "3",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Black wizard robe (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "3",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "3",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue d'hide body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "20",
    "stabdef": "45",
    "slashdef": "37",
    "crushdef": "50",
    "magicdef": "30",
    "rangedef": "45",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue d'hide body (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "20",
    "stabdef": "45",
    "slashdef": "37",
    "crushdef": "50",
    "magicdef": "30",
    "rangedef": "45",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue d'hide body (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "20",
    "stabdef": "45",
    "slashdef": "37",
    "crushdef": "50",
    "magicdef": "30",
    "rangedef": "45",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue elegant blouse",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue elegant shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue naval shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue wizard robe",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "3",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "3",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue wizard robe (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "3",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "3",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Blue wizard robe (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "3",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "3",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bob's black shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bob's blue shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bob's green shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bob's purple shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bob's red shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bomber jacket",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bronze chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "7",
    "slashdef": "11",
    "crushdef": "13",
    "magicdef": "-3",
    "rangedef": "9",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bronze platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "15",
    "slashdef": "14",
    "crushdef": "9",
    "magicdef": "-6",
    "rangedef": "14",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bronze platebody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "15",
    "slashdef": "14",
    "crushdef": "9",
    "magicdef": "-6",
    "rangedef": "14",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bronze platebody (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "15",
    "slashdef": "14",
    "crushdef": "9",
    "magicdef": "-6",
    "rangedef": "14",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Brown apron",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Brown naval shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Builder's shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Bunny top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Camo top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Carnillean armour",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "20",
    "slashdef": "14",
    "crushdef": "8",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Chicken wings",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Citizen top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Clown gown",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Clue hunter garb",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-2",
    "ranged": "2",
    "stabdef": "8",
    "slashdef": "9",
    "crushdef": "10",
    "magicdef": "4",
    "rangedef": "9",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Corrupted body (attuned)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "102",
    "slashdef": "102",
    "crushdef": "102",
    "magicdef": "102",
    "rangedef": "102",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 4
  },
  {
    "Name": "Corrupted body (basic)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "86",
    "slashdef": "86",
    "crushdef": "86",
    "magicdef": "86",
    "rangedef": "86",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 3
  },
  {
    "Name": "Corrupted body (perfected)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "124",
    "slashdef": "124",
    "crushdef": "124",
    "magicdef": "124",
    "rangedef": "124",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 5
  },
  {
    "Name": "Corrupted platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "21",
    "slashdef": "20",
    "crushdef": "12",
    "magicdef": "-6",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Cow top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Cream robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Crier coat",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Crystal body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-18",
    "ranged": "30",
    "stabdef": "34",
    "slashdef": "24",
    "crushdef": "32",
    "magicdef": "44",
    "rangedef": "53",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 3
  },
  {
    "Name": "Crystal body (attuned)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "102",
    "slashdef": "102",
    "crushdef": "102",
    "magicdef": "102",
    "rangedef": "102",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 4
  },
  {
    "Name": "Crystal body (basic)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "86",
    "slashdef": "86",
    "crushdef": "86",
    "magicdef": "86",
    "rangedef": "86",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 3
  },
  {
    "Name": "Crystal body (perfected)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "124",
    "slashdef": "124",
    "crushdef": "124",
    "magicdef": "124",
    "rangedef": "124",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 5
  },
  {
    "Name": "Dagon'hai robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "25",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "21",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 2
  },
  {
    "Name": "Dark infinity top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "22",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "22",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Dark tuxedo jacket",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Deadman's chest",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "+",
    "ranged": "+",
    "stabdef": "+",
    "slashdef": "+",
    "crushdef": "+",
    "magicdef": "+",
    "rangedef": "+",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Decorative armour (gold, platebody)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Decorative armour (magic top)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "20",
    "slashdef": "20",
    "crushdef": "20",
    "magicdef": "20",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Decorative armour (ranged top)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "20",
    "slashdef": "20",
    "crushdef": "20",
    "magicdef": "20",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Decorative armour (red, platebody)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "32",
    "slashdef": "31",
    "crushdef": "24",
    "magicdef": "-6",
    "rangedef": "31",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Decorative armour (white, platebody)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "46",
    "slashdef": "44",
    "crushdef": "38",
    "magicdef": "-6",
    "rangedef": "44",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Desert camo top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "0",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Desert shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Desert top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Desert top (overcoat)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Dharok's platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "122",
    "slashdef": "120",
    "crushdef": "107",
    "magicdef": "-6",
    "rangedef": "132",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Dragon chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "81",
    "slashdef": "93",
    "crushdef": "98",
    "magicdef": "-3",
    "rangedef": "82",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Dragon chainbody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "81",
    "slashdef": "93",
    "crushdef": "98",
    "magicdef": "-3",
    "rangedef": "82",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Dragon platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "109",
    "slashdef": "107",
    "crushdef": "97",
    "magicdef": "-6",
    "rangedef": "106",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Dragon platebody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "109",
    "slashdef": "107",
    "crushdef": "97",
    "magicdef": "-6",
    "rangedef": "106",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Dragonstone platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Druid's robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 4
  },
  {
    "Name": "Eggshell platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Elder chaos top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "10",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "8",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Elite void top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "45",
    "slashdef": "45",
    "crushdef": "45",
    "magicdef": "45",
    "rangedef": "45",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 3
  },
  {
    "Name": "Elven top (white vest)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Elven top (white)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Elven top (yellow vest)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Elven top (yellow)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Enchanted top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "20",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "20",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Evil chicken wings",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Farmer's jacket",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Farmer's shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Fighter torso",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-40",
    "ranged": "0",
    "stabdef": "62",
    "slashdef": "85",
    "crushdef": "62",
    "magicdef": "-10",
    "rangedef": "67",
    "str": 4,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Fremennik beige shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Fremennik blue shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Fremennik brown shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Fremennik grey shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Fremennik red shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Fremennik robe",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Frog-leather body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-5",
    "ranged": "10",
    "stabdef": "23",
    "slashdef": "26",
    "crushdef": "30",
    "magicdef": "15",
    "rangedef": "32",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Ghostly robe (top)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "5",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "5",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Gilded chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "63",
    "slashdef": "72",
    "crushdef": "78",
    "magicdef": "-3",
    "rangedef": "65",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Gilded d'hide body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "15",
    "stabdef": "40",
    "slashdef": "32",
    "crushdef": "45",
    "magicdef": "20",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Gilded platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Gold elegant blouse",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Gold elegant shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Golden apron",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Graahk top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "0",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Graceful top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Granite body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-22",
    "ranged": "-5",
    "stabdef": "87",
    "slashdef": "84",
    "crushdef": "79",
    "magicdef": "-6",
    "rangedef": "97",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Gravedigger top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Green d'hide body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "15",
    "stabdef": "40",
    "slashdef": "32",
    "crushdef": "45",
    "magicdef": "20",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Green d'hide body (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "15",
    "stabdef": "40",
    "slashdef": "32",
    "crushdef": "45",
    "magicdef": "20",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Green d'hide body (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "15",
    "stabdef": "40",
    "slashdef": "32",
    "crushdef": "45",
    "magicdef": "20",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Green elegant blouse",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Green elegant shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Green naval shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Green robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Grey naval shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Grey robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Guthan's platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "122",
    "slashdef": "120",
    "crushdef": "107",
    "magicdef": "-6",
    "rangedef": "132",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Guthix d'hide",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Guthix platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Guthix robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "4",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "4",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Ham shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Hardcore ironman platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "21",
    "slashdef": "20",
    "crushdef": "12",
    "magicdef": "-6",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Hardleather body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-4",
    "ranged": "8",
    "stabdef": "12",
    "slashdef": "15",
    "crushdef": "18",
    "magicdef": "6",
    "rangedef": "15",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Infinity top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "22",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "22",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Initiate hauberk",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "46",
    "slashdef": "44",
    "crushdef": "38",
    "magicdef": "-6",
    "rangedef": "44",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Inquisitor's hauberk",
    "stab": -3,
    "slash": -3,
    "crush": 12,
    "magic": "-11",
    "ranged": "-10",
    "stabdef": "67",
    "slashdef": "55",
    "crushdef": "71",
    "magicdef": "0",
    "rangedef": "35",
    "str": 4,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 2
  },
  {
    "Name": "Iron chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "-3",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Iron platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "21",
    "slashdef": "20",
    "crushdef": "12",
    "magicdef": "-6",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Iron platebody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "21",
    "slashdef": "20",
    "crushdef": "12",
    "magicdef": "-6",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Iron platebody (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "21",
    "slashdef": "20",
    "crushdef": "12",
    "magicdef": "-6",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Ironman platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "21",
    "slashdef": "20",
    "crushdef": "12",
    "magicdef": "-6",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Jungle camo top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "0",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Justiciar chestguard",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-40",
    "ranged": "-20",
    "stabdef": "132",
    "slashdef": "130",
    "crushdef": "117",
    "magicdef": "-16",
    "rangedef": "142",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 4
  },
  {
    "Name": "Karil's leathertop",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "47",
    "slashdef": "42",
    "crushdef": "50",
    "magicdef": "65",
    "rangedef": "57",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Khazard armour",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "9",
    "slashdef": "11",
    "crushdef": "10",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Kyatt top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "0",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Larupia top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "0",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Leather body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-2",
    "ranged": "2",
    "stabdef": "8",
    "slashdef": "9",
    "crushdef": "10",
    "magicdef": "4",
    "rangedef": "9",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Leather body (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-2",
    "ranged": "2",
    "stabdef": "8",
    "slashdef": "9",
    "crushdef": "10",
    "magicdef": "4",
    "rangedef": "9",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Lederhosen top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Light infinity top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "22",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "22",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Light tuxedo jacket",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Lumberjack top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Lunar torso",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "10",
    "ranged": "-10",
    "stabdef": "34",
    "slashdef": "22",
    "crushdef": "40",
    "magicdef": "12",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Medical gown",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Menaphite purple top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Menaphite red top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mime top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mithril chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "25",
    "slashdef": "35",
    "crushdef": "42",
    "magicdef": "-3",
    "rangedef": "27",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mithril platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "46",
    "slashdef": "44",
    "crushdef": "38",
    "magicdef": "-6",
    "rangedef": "44",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mithril platebody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "46",
    "slashdef": "44",
    "crushdef": "38",
    "magicdef": "-6",
    "rangedef": "44",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mithril platebody (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "46",
    "slashdef": "44",
    "crushdef": "38",
    "magicdef": "-6",
    "rangedef": "44",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Monk's robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Monk's robe top (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Monk's robe top (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Moonclan armour",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "5",
    "ranged": "-10",
    "stabdef": "5",
    "slashdef": "5",
    "crushdef": "5",
    "magicdef": "5",
    "rangedef": "-10",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Morrigan's leather body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "36",
    "stabdef": "61",
    "slashdef": "53",
    "crushdef": "66",
    "magicdef": "75",
    "rangedef": "62",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mourner top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mummy's body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Musketeer tabard",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mystic robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "20",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "20",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mystic robe top (dark)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "20",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "20",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mystic robe top (dusk)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "20",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "20",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Mystic robe top (light)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "20",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "20",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Obsidian platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "55",
    "slashdef": "78",
    "crushdef": "56",
    "magicdef": "-15",
    "rangedef": "60",
    "str": 3,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Ornate top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "-3",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Pink elegant blouse",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Pink elegant shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Pink robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Plague jacket",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Polar camo top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "0",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Priest gown (top)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 3
  },
  {
    "Name": "Prince tunic",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Princess blouse",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Proselyte hauberk",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 8
  },
  {
    "Name": "Prospector jacket",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Purple elegant blouse",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Purple elegant shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Purple naval shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Purple robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Pyromancer garb",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rangers' tunic",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "15",
    "stabdef": "6",
    "slashdef": "9",
    "crushdef": "12",
    "magicdef": "6",
    "rangedef": "6",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Red d'hide body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "25",
    "stabdef": "50",
    "slashdef": "42",
    "crushdef": "55",
    "magicdef": "40",
    "rangedef": "50",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Red d'hide body (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "25",
    "stabdef": "50",
    "slashdef": "42",
    "crushdef": "55",
    "magicdef": "40",
    "rangedef": "50",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Red d'hide body (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "25",
    "stabdef": "50",
    "slashdef": "42",
    "crushdef": "55",
    "magicdef": "40",
    "rangedef": "50",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Red elegant blouse",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Red elegant shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Red naval shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Red robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Robe of elidinis (top)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Robe top of darkness",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "20",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "20",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rock-shell plate",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rogue top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "10",
    "crushdef": "10",
    "magicdef": "10",
    "rangedef": "10",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Royal gown top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "63",
    "slashdef": "72",
    "crushdef": "78",
    "magicdef": "-3",
    "rangedef": "65",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune platebody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune platebody (h1)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune platebody (h2)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune platebody (h3)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune platebody (h4)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune platebody (h5)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Rune platebody (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Samurai shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "69",
    "slashdef": "67",
    "crushdef": "59",
    "magicdef": "10",
    "rangedef": "67",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Sandwich lady top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Santa jacket",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Saradomin d'hide",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Saradomin platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Saradomin robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "4",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "4",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Shade robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 5
  },
  {
    "Name": "Shayzien platebody (1)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-5",
    "ranged": "0",
    "stabdef": "16",
    "slashdef": "20",
    "crushdef": "22",
    "magicdef": "-2",
    "rangedef": "16",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Shayzien platebody (2)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-7",
    "ranged": "0",
    "stabdef": "20",
    "slashdef": "25",
    "crushdef": "30",
    "magicdef": "-3",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Shayzien platebody (3)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-8",
    "ranged": "0",
    "stabdef": "25",
    "slashdef": "32",
    "crushdef": "35",
    "magicdef": "-3",
    "rangedef": "22",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Shayzien platebody (4)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-9",
    "ranged": "0",
    "stabdef": "28",
    "slashdef": "35",
    "crushdef": "37",
    "magicdef": "-4",
    "rangedef": "25",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Shayzien platebody (5)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-10",
    "ranged": "0",
    "stabdef": "30",
    "slashdef": "37",
    "crushdef": "40",
    "magicdef": "-4",
    "rangedef": "27",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Shirt (brown)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Shirt (lilac)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Shirt (yellow)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Silly jester top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "5",
    "rangedef": "-5",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Skeletal top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "8",
    "ranged": "-10",
    "stabdef": "35",
    "slashdef": "25",
    "crushdef": "42",
    "magicdef": "15",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Skeleton shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Slave shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Snakeskin body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-5",
    "ranged": "12",
    "stabdef": "25",
    "slashdef": "28",
    "crushdef": "32",
    "magicdef": "15",
    "rangedef": "35",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Snow imp costume body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Spined body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "15",
    "stabdef": "40",
    "slashdef": "32",
    "crushdef": "45",
    "magicdef": "20",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Splitbark body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "10",
    "ranged": "-10",
    "stabdef": "36",
    "slashdef": "26",
    "crushdef": "42",
    "magicdef": "15",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Spookier robe",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Spooky robe",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Statius's platebody",
    "stab": 5,
    "slash": 5,
    "crush": 7,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "154",
    "slashdef": "145",
    "crushdef": "121",
    "magicdef": "-6",
    "rangedef": "157",
    "str": 5,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Steel chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "17",
    "slashdef": "25",
    "crushdef": "30",
    "magicdef": "-3",
    "rangedef": "19",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Steel platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "32",
    "slashdef": "31",
    "crushdef": "24",
    "magicdef": "-6",
    "rangedef": "31",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Steel platebody (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "32",
    "slashdef": "31",
    "crushdef": "24",
    "magicdef": "-6",
    "rangedef": "31",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Steel platebody (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "32",
    "slashdef": "31",
    "crushdef": "24",
    "magicdef": "-6",
    "rangedef": "31",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Stripy pirate shirt (beige)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Stripy pirate shirt (blue)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Stripy pirate shirt (brown)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Stripy pirate shirt (red)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Studded body",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-4",
    "ranged": "8",
    "stabdef": "18",
    "slashdef": "25",
    "crushdef": "22",
    "magicdef": "8",
    "rangedef": "25",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Studded body (g)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-4",
    "ranged": "8",
    "stabdef": "18",
    "slashdef": "25",
    "crushdef": "22",
    "magicdef": "8",
    "rangedef": "25",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Studded body (t)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-4",
    "ranged": "8",
    "stabdef": "18",
    "slashdef": "25",
    "crushdef": "22",
    "magicdef": "8",
    "rangedef": "25",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Teal robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Torag's platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "122",
    "slashdef": "120",
    "crushdef": "107",
    "magicdef": "-6",
    "rangedef": "132",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Tree top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Tribal top (blue)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Tribal top (brown)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Tribal top (pink)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Tribal top (yellow)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Turquoise robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Twisted coat (t1)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Twisted coat (t2)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Twisted coat (t3)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Ultimate ironman platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "21",
    "slashdef": "20",
    "crushdef": "12",
    "magicdef": "-6",
    "rangedef": "20",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Varrock armour 1",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "32",
    "slashdef": "31",
    "crushdef": "24",
    "magicdef": "-6",
    "rangedef": "31",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Varrock armour 2",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Varrock armour 3",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "46",
    "slashdef": "44",
    "crushdef": "38",
    "magicdef": "-6",
    "rangedef": "44",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Varrock armour 4",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "65",
    "slashdef": "63",
    "crushdef": "55",
    "magicdef": "-6",
    "rangedef": "63",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Verac's brassard",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-6",
    "ranged": "-2",
    "stabdef": "81",
    "slashdef": "95",
    "crushdef": "85",
    "magicdef": "0",
    "rangedef": "81",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 5
  },
  {
    "Name": "Vesta's chainbody",
    "stab": 5,
    "slash": 7,
    "crush": 7,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "120",
    "slashdef": "131",
    "crushdef": "145",
    "magicdef": "-3",
    "rangedef": "140",
    "str": 6,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Void knight top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "45",
    "slashdef": "45",
    "crushdef": "45",
    "magicdef": "45",
    "rangedef": "45",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Vyrewatch top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "White apron",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "White chainbody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "0",
    "stabdef": "22",
    "slashdef": "32",
    "crushdef": "39",
    "magicdef": "-3",
    "rangedef": "24",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "White elegant blouse",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "White platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "41",
    "slashdef": "40",
    "crushdef": "30",
    "magicdef": "-6",
    "rangedef": "40",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Wood camo top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "10",
    "slashdef": "15",
    "crushdef": "19",
    "magicdef": "0",
    "rangedef": "12",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Woven top (blue)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Woven top (brown)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Woven top (yellow)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Xerician top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "12",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "10",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Yak-hide armour (top)",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-5",
    "ranged": "0",
    "stabdef": "25",
    "slashdef": "20",
    "crushdef": "15",
    "magicdef": "-2",
    "rangedef": "25",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Yellow robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "2",
    "crushdef": "2",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Zamorak d'hide",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-15",
    "ranged": "30",
    "stabdef": "55",
    "slashdef": "47",
    "crushdef": "60",
    "magicdef": "50",
    "rangedef": "55",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Zamorak monk top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "2",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "3",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 3
  },
  {
    "Name": "Zamorak platebody",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "-30",
    "ranged": "-10",
    "stabdef": "82",
    "slashdef": "80",
    "crushdef": "72",
    "magicdef": "-6",
    "rangedef": "80",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 1
  },
  {
    "Name": "Zamorak robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "4",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "4",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 6
  },
  {
    "Name": "Zombie shirt",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "0",
    "ranged": "0",
    "stabdef": "0",
    "slashdef": "0",
    "crushdef": "0",
    "magicdef": "0",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  },
  {
    "Name": "Zuriel's robe top",
    "stab": 0,
    "slash": 0,
    "crush": 0,
    "magic": "35",
    "ranged": "-10",
    "stabdef": "63",
    "slashdef": "45",
    "crushdef": "74",
    "magicdef": "35",
    "rangedef": "0",
    "str": 0,
    "rangedstr": 0,
    "magicstr": 0,
    "prayer": 0
  }
]
export default body;